--- #YAML:1.0
name: Template-Plugin-AudioFile-Info
version: 0.01
license: perl
distribution_type: module
requires:
  AudioFile::Info: 0
  Template: 0
  perl: 5.6.0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Template::Plugin::AudioFile::Info:
    file: lib/Template/Plugin/AudioFile/Info.pm
    version: 0.01
generated_by: Module::Build version 0.20
